export const skillSuggestionOptions = [
  "Python",
  "Java",
  "JavaScript",
  "TypeScript",
  "C",
  "C++",
  "C#",
  "SQL",
  "MySQL",
  "PostgreSQL",
  "MongoDB",
  "SQLite",
  "HTML",
  "CSS",
  "React",
  "Angular",
  "Vue.js",
  "Node.js",
  "Express.js",
  "Django",
  "Flask",
  "FastAPI",
  "Spring Boot",
  "REST API",
  "Git",
  "GitHub",
  "Docker",
  "Kubernetes",
  "AWS",
  "Azure",
  "Google Cloud",
  "Linux",
  "DevOps",
  "CI/CD",
  "Data Structures",
  "Algorithms",
  "Machine Learning",
  "Deep Learning",
  "NLP",
  "Computer Vision",
  "Generative AI",
  "TensorFlow",
  "PyTorch",
  "Scikit-learn",
  "Pandas",
  "NumPy",
  "Statistics",
  "Data Analysis",
  "Data Science",
  "Data Engineering",
  "ETL",
  "Excel",
  "Power BI",
  "Tableau",
  "Data Visualization",
  "Business Analysis",
  "Agile",
  "Scrum",
  "Project Management",
  "Product Management",
  "UI/UX Design",
  "Figma",
  "Graphic Design",
  "Digital Marketing",
  "SEO",
  "Google Ads",
  "Social Media Marketing",
  "Content Writing",
  "Copywriting",
  "Email Marketing",
  "Sales",
  "Lead Generation",
  "CRM",
  "Negotiation",
  "Customer Support",
  "Communication",
  "Presentation",
  "Recruiting",
  "HR",
  "Onboarding",
  "Accounting",
  "Finance",
  "Tally",
  "GST",
  "Bookkeeping",
  "Teaching",
  "Lesson Planning",
  "Data Entry",
  "MS Office",
  "Cybersecurity",
  "Network Security",
  "Manual Testing",
  "Automation Testing",
  "Selenium",
  "Kotlin",
  "Swift",
  "Ruby",
  "Ruby on Rails",
  "PHP",
  "Laravel",
  "Rust",
  "Go",
  "Dart",
  "Flutter",
  "React Native",
  "Mobile App Development",
  "iOS Development",
  "Android Development",
  "Redis",
  "GraphQL",
  "Next.js",
  "Nuxt.js",
  "Svelte",
  "Tailwind CSS",
  "Bootstrap",
  "SASS",
  "Webpack",
  "Vite",
  "Firebase",
  "Supabase",
  "Elasticsearch",
  "Kafka",
  "RabbitMQ",
  "Microservices",
  "System Design",
  "Terraform",
  "Ansible",
  "Jenkins",
  "Jira",
  "Confluence",
  "Trello",
  "Asana",
  "Notion",
  "Google Analytics",
  "Mixpanel",
  "Amplitude",
  "Salesforce",
  "HubSpot",
  "Zendesk",
  "Intercom",
  "Stripe",
  "PayPal API",
  "Shopify",
  "WordPress",
  "Magento",
  "E-commerce",
  "Supply Chain Management",
  "Logistics",
  "Inventory Management",
  "Quality Assurance",
  "Penetration Testing",
  "Ethical Hacking",
  "Cryptography",
  "Blockchain",
  "Web3",
  "Smart Contracts",
  "Solidity",
  "AR/VR",
  "Unity",
  "Unreal Engine",
  "Game Development",
  "3D Modeling",
  "Blender",
  "Adobe Creative Suite",
  "Photoshop",
  "Illustrator",
  "Premiere Pro",
  "After Effects",
  "Video Editing",
  "Photography",
  "Public Speaking",
  "Leadership",
  "Team Management",
  "Problem Solving",
  "Critical Thinking",
  "Time Management",
  "Event Planning",
  "Public Relations",
];

export const popularSkillSuggestions = [
  "Python",
  "SQL",
  "Machine Learning",
  "React",
  "Java",
  "Excel",
  "Power BI",
  "AWS",
  "Communication",
  "Digital Marketing",
  "Sales",
  "HR",
  "Accounting",
  "Customer Support",
  "Content Writing",
];
